package example.model;

import de.bybackfish.sql.annotation.*;
import de.bybackfish.sql.core.DatabaseModel;
import de.bybackfish.sql.util.Lazy;

import java.util.List;

// Create a model that represents an "Employee" from the "employee" table

@Table("employee")
@SuppressWarnings("unused")
public class Employee extends DatabaseModel {
    public String name;

    // Primary Key, used to distinct between rows.
    // Every Model should have one if you want to update rows.
    @PrimaryKey
    @AutoGenerated
    @ForeignKey(targetTable = "link", targetColumn = "employee_id")
    public int id;

    // Lazy is used to automatically load the relation to the target table when needed.
    // @LazyLoaded takes in the field of this class that has the @ForeignKey annotation.
    @LazyLoaded(value = "id")
    public Lazy<List<EmployeeDepartmentLink>> department;

    @Field("type")
    public EmployeeType type;

    public enum EmployeeType {
        ADMIN,
        GUEST,
        STAFF,
        MANAGER
    }
}
